# Generated by Django 4.2.3 on 2024-05-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Nom')),
                ('image', models.ImageField(blank=True, null=True, upload_to='process_images/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Process',
                'verbose_name_plural': 'Produits',
                'db_table': 'process_process',
                'ordering': ['name'],
            },
        ),
    ]
