# Generated by Django 4.2.3 on 2024-05-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process',
            options={'ordering': ['usability'], 'verbose_name': 'Process', 'verbose_name_plural': 'Produits'},
        ),
        migrations.RemoveField(
            model_name='process',
            name='name',
        ),
        migrations.AddField(
            model_name='process',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='process',
            name='etat',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Etat'),
        ),
        migrations.AddField(
            model_name='process',
            name='score',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='process',
            name='usability',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Usability'),
        ),
    ]
