# Generated by Django 4.2.3 on 2024-05-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_alter_process_options_remove_process_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='brand',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='process',
            name='etat',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Etat'),
        ),
        migrations.AlterField(
            model_name='process',
            name='score',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='process',
            name='usability',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Usability'),
        ),
    ]
