# Generated by Django 4.2.3 on 2024-06-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_alter_process_brand_alter_process_etat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
    ]
