# Generated by Django 4.2.3 on 2024-06-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0004_alter_process_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/process_images/', verbose_name='Image'),
        ),
    ]
